name: Build & Deploy to GitHub Pages (Personal Site)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build site
        run: bun run build

      - name: Deploy to GitHub Pages
        run: |
          touch dist/.nojekyll
          cp public/CNAME dist/CNAME || true
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd dist
          git init
          git remote add origin https://github.com/soontobefound/soontobefound.github.io.git
          git checkout -b main
          git add .
          git commit -m "Deploy"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/soontobefound/soontobefound.github.io.git main
